server:
  port: 8080
  max-http-header-size: 102400
mybatis-plus:
  mapper-locations: classpath:com/dkm/*/dao/mapper/*.xml
spring:
  profiles:
    active: test
  application:
    name: chat-service
  jmx:
    enabled: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

app:
  workerId: 9
  dataCenterId: 1
