spring:
  rabbitmq:
    host: 192.168.10.133
    username: guest
    password: guest
    port: 5672
    virtual-host: /
    publisher-confirms: true
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
  redis:
    host: 192.168.10.133
    timeout: 2000
    jedis:
      pool:
        min-idle: 1
        max-active: 20
        max-wait: 1000


app:
  workerId: 1
  dataCenterId: 2

RSA:
  myPublicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDf5knDRg+BTq+mPVlqt43yu/FHK+RCEpwRODmIQZoSskOfClzO/dba95fxml00jB7/6UQeM1XgrPSdDKKx8HDaf6/e8cC6osPLypEqFXLCH/bVD0NUAKF7aYyRNsvW17evFJGg/NQTcXU4m9Oj1cetuxENaHt07jtkaQSsQ2n1HQIDAQAB
  kePrivateKey:

